spring.application.name=PizzaParadise
spring.datasource.url=jdbc:mysql://localhost:3306/PizzaParadise
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always

spring.thymeleaf.cache=false

server.port=8080
